### ISSUE TITLE
`YamlCspConfig::YamlLoader::DIRECTIVES` is missing some CSP directives

### ISSUE THREAD

**Issue by stevegeek** [stevegeek/yaml_csp_config#2]
The array `YamlCspConfig::YamlLoader::DIRECTIVES` is meant to specify all the various CSP directives that might be used. This list is used when determining the names of ENV vars for overrides. 

For a list of all CSP directives see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy  

Our list is incomplete.

The easy way to fix this is to just update the list to include all directives.

Maybe a better, but more involved solution, would be to depend on those defined in Rails in `ActionDispatch`, eg see the `DIRECTIVES` array defined in https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/content_security_policy.rb#L143

Note that that list in `ActionDispatch::ContentSecurityPolicy::DIRECTIVES` does not include every directive, as some directives are handled in a specific way by `ActionDispatch::ContentSecurityPolicy` & hence instead are implemented as methods directly, eg `sandbox` is implemented explicitly here https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/content_security_policy.rb#L265 ... 

Therefore we need to take into account these extra directives not defined in `DIRECTIVES`, that are: `[:navigate_to, :sandbox, :report_uri, :report_to, :upgrade_insecure_requests]` and the deprecated ones `[:block_all_mixed_content, :plugin_types,  :referrer]`

**Comment by mhakeem** [comment]
Hi Steve,

I created a PR and added the missing CSP directives. I didn't see any contribution guidelines in your repo so I just went the "easy way" mentioned here. Let me know if that does the job and if you have any other comments. Thanks :)

**Comment by stevegeek** [comment]
@mhakeem thanks so much for the PR and sorry for the delay. I was unavailable for a few days. I will try look at this asap
